### ISSUE TITLE
Also apply faces *between* delimiters (i.e. do rainbow-blocks)

### ISSUE THREAD

**Issue by jonaskoelker** [Fanael/rainbow-delimiters#24]
I am hoping to get my emacs to behave as follows: pick the foreground of text based on token type (keyword, string, comment, etc.) and the background based on scope.

It would be great if rainbow-delimiters could do that. That is, if it had customizeable faces which were applied _between_ delimiters.

Rainbow-blocks does this, but it clobbers the foreground color from my major mode. To that end, I filed https://github.com/istib/rainbow-blocks/issues/6 against the project. However, it appears dead (last commit was two years ago), whereas rainbow-delimiters doesn't.

**Comment by Fanael** [comment]
You can try https://github.com/e-c-d/rainbow-delimiters. I *won't* merge it, no matter what, because I believe it goes against the spirit of rainbow-*delimiters*. Your best chance is to convince the author of this fork to release it under the name of rainbow-blocks or similar.

As for the old rainbow-blocks, lemme just say it's a fork of an ancient and buggy version of rainbow-delimiters, never updated since forking, and leave it at that.

**Comment by jonaskoelker** [comment]
Thanks for the pointer to the e-c-d rainbow-delimiters. I believe I can make it do what I want, with a bit of fiddling and hacking. Cheers :-)

**Comment by alphapapa** [comment]
@jonaskoelker You may find this helpful: https://github.com/alphapapa/prism.el
