### ISSUE TITLE
parenthesis not colored in latex mode

### ISSUE THREAD

**Issue by dinojr** [Fanael/rainbow-delimiters#26]
I'm running rainbow-delimiters 20160430 from melpa. In a LaTeX buffer, only square and curly brackets are colored. Parenthesis aren't. Why is that  ?

Please see the attached screenshot, from emacs -Q.
![rainbow](https://cloud.githubusercontent.com/assets/2698065/18669110/a972bede-7f39-11e6-81b6-645bf35e7026.png)

**Comment by Fanael** [comment]
Cannot reproduce. What's the version of Emacs?

**Comment by dinojr** [comment]
The problem arises with both Emacs24 et 25 but I discovered it must be a conflict with another package: if I don't run (package-initialize) but (load "~/.emacs.d/elpa/rainbow-delimiters-20160430.2358/rainbow-delimiters.el"), everything is fine.

**Comment by yanghaoxie** [comment]
It seems this problem is related to `auctex`'s `font-lock`. If you disable `auctex` `font-lock` by `(setq TeX-install-font-lock 'ignore)`, the problem is solved.

But, since I lack the skills of `emacs-lisp`, I think I may not find a way to make these two awesome packages compatible.

I am really appreciate it if you can help me to solve this problem.
