### ISSUE TITLE
#_ comments in Clojure do not disable delimiter highlight

### ISSUE THREAD

**Issue by dottedmag** [Fanael/rainbow-delimiters#29]
Apparently `clojure-mode` is doing some tricks with `#_` reader expression highlight: sexp is highlighted using `font-lock-comment-face`, but rainbow-delimiters are not disabled inside.

See the screenshot:

<img width="375" alt="screen shot 2017-02-22 at 22 09 00" src="https://cloud.githubusercontent.com/assets/16120/23232439/8ae998ca-f94b-11e6-8dad-373385272955.png">

**Comment by Fanael** [comment]
This is a bug in clojure-mode: this is not a comment, as `(nth 4 (syntax-pps))` is `nil`, it's merely fontified like one. Clojure-mode should set appropriate [`syntax-table` text properties](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Properties.html) on this syntax so that Emacs actually understands it's a comment, please report it there.
