### ISSUE TITLE
Condition recognized as closing bracket in elisp source code block inside org-mode

### ISSUE THREAD

**Issue by technician77** [Fanael/rainbow-delimiters#42]
Hello,
first I'm not a coder, so elisp always gives me a hard time. I use an 'orged' init file, where I have this block below. The > ist recognized as a orphaned closing bracket. In a standard elisp buffer, like scratch, this problem does not occur. How do I fix this?
```
* Test
#+BEGIN_SRC emacs-lisp
    (define-ibuffer-column size-h
      (:name "Size" :inline t)
      (cond
       ((> (buffer-size) 1000000) (format "%7.1fM" (/ (buffer-size) 1000000.0)))
       ((> (buffer-size) 100000) (format "%7.0fk" (/ (buffer-size) 1000.0)))
       ((> (buffer-size) 1000) (format "%7.1fk" (/ (buffer-size) 1000.0)))
       (t (format "%8d" (buffer-size)))))
#+END_SRC
```

**Comment by Fanael** [comment]
I can't reproduce this in org-mode in my setup, so the problem is likely caused by a third party package or your own customization, or possibly the version of org-mode you have installed, messing up the syntax table and/or syntax properties of the text itself. I can't help you more than just suggesting bisecting your config to find the culprit.
