### ISSUE TITLE
Mismatches quotes for references in perl

### ISSUE THREAD

**Issue by chy-causer** [Fanael/rainbow-delimiters#58]
Using cperl mode, the following is legal, but rainbow-delimiters treats this as mismatched brackets

```perl
my $variable = \["Hello there"];
```

In perl, the backslash is not to denote an escaped bracket, but instead is to assign a reference to the arrayref rather than assign the arrayref directly. A reference to a reference doesn't get used much, but a prominent module that uses this is SQL::Abstract.

I took a look at rainbow-delimiters source and it looks like the dual character syntax code is general and so there doesn't seem to be a nice way to tell it to treat perl code differently from other languages. However I felt I should report this just in case there's something I'm missing and there's an easy patch that could allow the code snippet above to not result in a syntax error.

Thanks for this module BTW. It's great.

**Comment by Fanael** [comment]
The problem here is that the backslash is set as an escape character in `cperl-mode`'s syntax table, but it doesn't have a `syntax-propertize-function` to override that syntax type for backslashes that are not escape characters, like the one here.

`rainbow-delimiters` is just the messenger here, all other emacs lisp code that relies on syntax properties is affected as well, for example `backward-sexp` (`C-M-b`) signals an unbalanced parentheses error if called with point at the semicolon.

The proper place to issue a bug report to is thus `cperl-mode`.
