### ISSUE TITLE
Double duty parentheses 

### ISSUE THREAD

**Issue by danielsz** [Fanael/rainbow-delimiters#63]
Given a language where parentheses are part of a two-character comment (see syntax table below), it appears that `rainbow-delimiters` will leave those comments alone (which is good), but will also leave alone all other instances of parentheses, even when they are used by themselves as a grouping construct.

Thank you for for your work (and for further advice/corrections/suggestions/ideas).

````emacs-lisp
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?\( ". 1" table)
    (modify-syntax-entry ?\) ". 4" table)
    (modify-syntax-entry ?* ". 23" table)
    table) 
````

**Comment by Fanael** [comment]
This is the correct behavior, as this syntax table indicates that parentheses are generic unpaired punctuation, rather than a grouping pair; rainbow-delimiters is only concerned with the latter.

What you probably want is this syntax table instead:
```emacs-lisp
(let ((table (make-syntax-table)))
  (modify-syntax-entry ?\( "()1" table)
  (modify-syntax-entry ?\) ")(4" table)
  (modify-syntax-entry ?* ". 23" table)
  table)
```
This works just fine for me:
![x](https://user-images.githubusercontent.com/270470/130232670-5f10819c-aeb2-4e22-a19a-f28caa961df8.png)

**Comment by danielsz** [comment]
That is such a perfect answer. Thank you and apologies for the noise .
