### ISSUE TITLE
In Orgmode mismatching with => in SRC code segments

### ISSUE THREAD

**Issue by scofild429** [Fanael/rainbow-delimiters#72]
In other major mode(js or ts), this is not the problem, but in src code segment, the mismatching occurs after the first =>
![Screenshot from 2022-11-28 23-59-09](https://user-images.githubusercontent.com/30410413/204398639-0fc544e4-95ee-42b7-904d-501f5442614c.png)

**Comment by Fanael** [comment]
This is a problem with org-mode setting syntactical properties of text incorrectly: since it doesn't *require* `>` or `(` to be paired with its corresponding opening/closing character, it should not mark them as pairable delimiters in its syntax table, except maybe in contexts where they *are* paired, by marking those particular uses with appropriate text properties.

This doesn't only affect rainbow-delimiters, but also potentially any other package that relies on the Emacs syntax engine, depending on how tolerant of incorrect syntax it is.

To quote myself from https://github.com/Fanael/rainbow-delimiters/issues/64#issuecomment-912900250:

> Rainbow-delimiters is quite intentionally simply following what the Emacs syntax engine tells it — the same syntax engine that's used by `{backward,forward}-sexp` and `show-paren-mode` and everything that calls `syntax-ppss` and so on — both for simplicity reasons and consistency with the rest of the ecosystem. Changing that would require significant effort that's very similar to #1: not impossible, but very difficult to ensure correctness of, because there are approximately seventy five billion edge cases to consider.
