### ISSUE TITLE
Deactivate when in Python regex strings

### ISSUE THREAD

**Issue by buhtz** [Fanael/rainbow-delimiters#73]
Imagine regex strings like this in Python source code

    r"(?:^| )=(.*?)=(?:[ .,;:\-?!)}\"']|$)"

I can easy understand why your mode has "problems" with it. The point is that your mode extremly slow down the whole emacs system and nearly freeze it when the block/cursor is in that string.
OK, I'm using a RasperryPi 4 (Debian 11, SSH shell and running XRDP) which is of course quit slow.

I don't know much about Lisp and Emacs. But maybe you can find a way
 - to recognize such strings and ignore them
 - or to have kind of a fail check if it runs in "heavy situations". Kind of an escape switch in a recursion.

**Comment by Fanael** [comment]
I cannot reproduce any slowness with just this literal, can you provide a more substantial amount of code that shows the issue? Does it happen even under `emacs -Q` with nothing but rainbow-delimiters loaded?

> to recognize such strings and ignore them

rainbow-delimiters already ignores all string literals and comments.

**Comment by buhtz** [comment]
> rainbow-delimiters already ignores all string literals and comments.

Mhm... Mysterious. The slow/freeze appeared when I disabled the rainbow mode.
Are you sure that your mode can do recognize that string as a literal? There are `"` and `'` in that string, too.

**Comment by Fanael** [comment]
> Mhm... Mysterious. The slow/freeze appeared when I disabled the rainbow mode.

That's why I recommended testing in a clean environment, using `emacs -Q`. Emacs is one massive pile of global mutable state, just about any piece of code can mess something up and cause problems in a seemingly unrelated place.

> Are you sure that your mode can do recognize that string as a literal?

Yes. rainbow-delimiters doesn't do any of it itself, it asks the [Emacs built-in syntax machinery](https://www.gnu.org/software/emacs/manual/html_node/elisp/Position-Parse.html) for the information. If the major mode is well-behaved, which `python-mode` appears to be, strings will be recognized as strings even in presence of potentially confusing characters and escape sequences.

**Comment by sogaiu** [comment]
@Fanael

Regarding:

> Yes. rainbow-delimiters doesn't do any of it itself, it asks the [Emacs built-in syntax machinery](https://www.gnu.org/software/emacs/manual/html_node/elisp/Position-Parse.html) for the information. If the major mode is well-behaved, which python-mode appears to be, strings will be recognized as strings even in presence of potentially confusing characters and escape sequences.

I'm experiencing a similar issue with a different language.  In my case, I think one of the factors may be that the major mode for it didn't quite get the syntax stuff quite right (known issue which despite multiple attempts hasn't been resolved upstream).

I've got a separate tree-sitter-based mode for the language and am thinking to apply the machinery there instead to identify comments and strings (and potentially other bits) instead of relying on what is specified by the original major mode.

Based on your comment above, I found this code: https://github.com/Fanael/rainbow-delimiters/blob/a32b39bdfe6c61c322c37226d66e1b6d4f107ed0/rainbow-delimiters.el#L204-L227

Is that part of what you were referring to by "it asks the Emacs built-in syntax machinery"?

**Comment by Fanael** [comment]
That's part of it, there's also `syntax-ppss`, `skip-syntax-forward` and `parse-partial-sexp` in `rainbow-delimiters--propertize`.

> I've got a separate tree-sitter-based mode for the language and am thinking to apply the machinery there instead to identify comments and strings (and potentially other bits) instead of relying on what is specified by the original major mode.

It should be fine to just modify the major mode's [syntax table](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Tables.html) behind its back to fix whatever needs fixing, and if that's not enough, [apply syntax properties dynamically](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Properties.html) according to the information from tree-sitter.

**Comment by sogaiu** [comment]
Thanks a lot for elaborating and the suggestions.

**Comment by sogaiu** [comment]
@Fanael 

To follow up a bit, I had some success with your last suggestion of applying syntax properties dynamically in combination with leveraging Emacs 29+'s tree-sitter support.

So far the result seems to be an overall improvement over the previous situation.

Thanks again for your help (and rainbow-delimiters!).
